// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IERC7857$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IERC7857";
  readonly sourceName: "src/interfaces/IERC7857.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"tokenId","type":"uint256"},{"indexed":true,"internalType":"address","name":"to","type":"address"},{"indexed":false,"internalType":"string","name":"metadataURI","type":"string"}],"name":"AgentMinted","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"tokenId","type":"uint256"},{"indexed":true,"internalType":"address","name":"from","type":"address"},{"indexed":true,"internalType":"address","name":"to","type":"address"}],"name":"AgentTransferVerified","type":"event"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/interfaces/IERC7857.sol";
  readonly buildInfoId: "solc-0_8_28-8e57c69064e09c2ee5831877a6700258a72b4c6d";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IERC7857"]: IERC7857$Type;
    ["src/interfaces/IERC7857.sol:IERC7857"]: IERC7857$Type;
  }
}