import { useEffect, useRef, useState } from "react";
import { Icon, Mark } from "./Identity";
import CoinFlip from "./CoinFlip";

export default function Landing({login,loading,error}:{login:()=>void;loading:boolean;error:string|null}) {
 const root=useRef<HTMLDivElement>(null);
 const [motion,setMotion]=useState(true);
 const [mobileNav,setMobileNav]=useState(false);
 useEffect(()=>{const media=window.matchMedia("(prefers-reduced-motion: reduce)");setMotion(!media.matches);const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add("visible");}),{threshold:.12});root.current?.querySelectorAll(".reveal").forEach(el=>observer.observe(el));return ()=>observer.disconnect();},[]);
 const connect=()=>{if(!loading)login();};
 return <div ref={root} className={`landing ${motion?"motion-on":"motion-off"}`} onMouseMove={e=>{if(!motion)return;const rect=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty("--mx",`${(e.clientX/rect.width-.5)*12}px`);e.currentTarget.style.setProperty("--my",`${(e.clientY/window.innerHeight-.5)*10}px`);}}>
 <CoinFlip/>
 <a className="skip-link" href="#main">Skip to content</a>
 <header className="landing-nav wrap"><a className="brand" href="#"><Mark/><span>mercury<span className="brand-dot">.</span></span></a><nav className={mobileNav?"open":""} aria-label="Main navigation"><a href="#ecosystem" onClick={()=>setMobileNav(false)}>Ecosystem</a><a href="#how-it-works" onClick={()=>setMobileNav(false)}>How it works</a><a href="#ownership" onClick={()=>setMobileNav(false)}>Ownership <span className="small-arrow">↗</span></a></nav><div className="nav-actions"><button className="motion-button" onClick={()=>setMotion(!motion)} aria-pressed={motion} title={motion?"Pause animations":"Enable animations"} aria-label={motion?"Pause animations":"Enable animations"}>{motion?"Ⅱ":"▷"}</button><button className="button nav-cta" onClick={connect} disabled={loading}>{loading?"Connecting…":"Launch app"}<Icon name="arrow"/></button><button className="icon-button landing-menu" onClick={()=>setMobileNav(!mobileNav)} aria-expanded={mobileNav} aria-label="Toggle navigation"><Icon name="menu"/></button></div></header>
 <main id="main"><section className="hero wrap"><div className="hero-copy"><div className="hero-kicker"><span className="status-dot"/>THE NEXT FRONTIER OF AGENT OWNERSHIP <Icon name="arrow"/></div><h1>Intelligence.<br/>With <span className="silver-text">ownership.</span></h1><p className="hero-description">An economy of agents. A universe of possibility.<br/>Create, discover, and own AI agents with an identity<br className="desktop-break"/> and a wallet of their own.</p><div className="hero-actions"><button onClick={connect} disabled={loading} className="button primary">{loading?"Connecting wallet…":"Enter the agent economy"}<Icon name="arrow"/></button><a href="#how-it-works" className="text-button"><span className="play-circle">▶</span>See how it works</a></div>{error&&<div className="auth-error" role="alert"><Icon name="wallet"/><span>{error}</span><button onClick={connect}>Try again</button></div>}<div className="hero-footnote"><span className="tiny-avatars"><i>M</i><i>✦</i><i>↗</i></span><span>One agent. Its own identity. <strong>Your ownership.</strong></span></div></div>
 <div className="hero-scene" aria-label="Metallic Mercury core with orbiting cryptocurrency symbols"><div className="scene-halo"/><img src="/mercury-hero.png" alt="Sculptural silver Mercury emblem suspended among glowing orbital rings" className="hero-art"/><div className="orbital-ring ring-a"/><div className="orbital-ring ring-b"/><div className="crypto-coin bitcoin" aria-hidden="true">₿</div><div className="crypto-coin ethereum" aria-hidden="true">♦</div><div className="crypto-coin doge" aria-hidden="true">Ð</div><div className="scene-label label-top"><span className="status-dot"/>AGENT IDENTITY</div><div className="scene-label label-bottom"><Icon name="shield"/>OWNERSHIP, ON-CHAIN</div><span className="scene-coordinate">MRC—001 / ORBITAL SYSTEM</span></div><div className="hero-bottom"><span><span className="blue-dash"/> BUILT FOR THE AGENT ECONOMY</span><a href="#ecosystem">SCROLL TO EXPLORE <span>↓</span></a></div></section>
 <div className="technology-strip"><div className="wrap"><span>THE FOUNDATION</span><strong><Icon name="layers"/>On-chain identity</strong><strong><Icon name="wallet"/>Agent wallets</strong><strong><Icon name="globe"/>Open marketplace</strong><strong><Icon name="shield"/>Ownership history</strong></div></div>
 <section id="ecosystem" className="ecosystem wrap section-space"><div className="section-heading reveal"><div><p className="eyebrow">01 / THE ECOSYSTEM</p><h2>Not just an agent.<br/><span className="muted">An asset of your own.</span></h2></div><p>Everything an agent needs to join the economy.<br/>Everything you need to make it yours.</p></div><div className="feature-grid">
 <article className="feature-card feature-identity reveal"><div className="feature-art identity-art" aria-hidden="true"><div className="id-orbit"/><div className="id-card"><Mark/><span>MERCURY AGENT</span><strong>Identity, secured.</strong><div className="id-barcode">ⅡⅠⅡⅠⅢⅠⅡⅢⅡⅠⅡⅠ</div></div><span className="art-tag"><Icon name="check"/>ONE UNIQUE IDENTITY</span></div><div className="feature-copy"><span className="feature-num">01</span><h3>Created to be yours.</h3><p>Define a persona, publish your agent, and give it a distinct on-chain identity.</p><button className="inline-link" onClick={connect}>Open Agent Studio <Icon name="arrow"/></button></div></article>
 <article className="feature-card reveal"><div className="feature-art wallet-art" aria-hidden="true"><div className="wallet-orbit"/><div className="wallet-glass"><Icon name="wallet"/><span>AGENT WALLET</span><strong>One agent.<br/>Its own account.</strong><span className="wallet-code">0x•••• / TOKEN-BOUND</span></div><div className="floating-eth">♦</div></div><div className="feature-copy"><span className="feature-num">02</span><h3>A wallet that belongs.</h3><p>A dedicated token-bound account connects your agent to its assets and ownership.</p><a href="#ownership" className="inline-link">Explore ownership <Icon name="arrow"/></a></div></article>
 <article className="feature-card reveal"><div className="feature-art market-art" aria-hidden="true"><div className="mini-agent a"><span>✧</span><i>Discover</i></div><div className="mini-agent b"><span>◈</span><i>Connect</i></div><div className="mini-agent c"><span>✺</span><i>Own</i></div></div><div className="feature-copy"><span className="feature-num">03</span><h3>Meet your next agent.</h3><p>Explore published agents, understand their purpose, and find your place in the marketplace.</p><button className="inline-link" onClick={connect}>Explore marketplace <Icon name="arrow"/></button></div></article>
 </div></section>
 <section id="how-it-works" className="process-section section-space"><div className="wrap"><div className="section-heading reveal"><div><p className="eyebrow">02 / FROM IDEA TO OWNERSHIP</p><h2>Your agent.<br/><span className="muted">Its next chapter.</span></h2></div><p>A connected lifecycle, from the first idea<br/>to the next owner.</p></div><div className="process-grid">{[{n:"01",icon:"spark",title:"Create",desc:"Give your agent a name, a persona, and a purpose."},{n:"02",icon:"wallet",title:"Provision",desc:"Connect its identity with a dedicated agent wallet."},{n:"03",icon:"compass",title:"Discover & trade",desc:"Publish to the marketplace. Find its next owner."},{n:"04",icon:"shield",title:"Follow ownership",desc:"Inspect the on-chain record as ownership changes."}].map(step=><article className="process-step reveal" key={step.n}><div><span>{step.n}</span><Icon name={step.icon}/></div><h3>{step.title}</h3><p>{step.desc}</p></article>)}</div></div></section>
 <section id="ownership" className="ownership-section wrap section-space"><div className="ownership-copy reveal"><p className="eyebrow">03 / A RECORD THAT FOLLOWS</p><h2>Ownership changes.<br/><span className="muted">The story stays.</span></h2><p>An agent’s identity goes beyond a profile. Follow its owner, wallet, and transaction history from one place.</p><ul><li><Icon name="check"/>A distinct identity for every agent</li><li><Icon name="check"/>A wallet connected to that identity</li><li><Icon name="check"/>An inspectable ownership record</li></ul><button className="button secondary" onClick={connect}>Explore the workspace <Icon name="arrow"/></button></div><div className="ownership-visual reveal"><div className="record-header"><Mark/><span>OWNERSHIP LIFECYCLE</span><span className="concept-badge">Illustration</span></div><div className="record-core"><div className="record-orb"><Mark/></div><div><span>MERCURY AGENT</span><h3>One identity.<br/>Across every handoff.</h3></div></div><div className="record-route"><span><Icon name="code"/>Chain</span><i/><span><Icon name="layers"/>Record</span><i/><span><Icon name="grid"/>Workspace</span></div><div className="record-footer"><Icon name="shield"/>The ownership journey, connected.</div></div></section>
 <section className="final-cta wrap reveal"><div className="cta-orbit" aria-hidden="true"/><p className="eyebrow">THE NEXT CHAPTER IS YOURS</p><h2>Make intelligence<br/><span className="silver-text">your own.</span></h2><button className="button primary" onClick={connect} disabled={loading}>Launch Mercury <Icon name="arrow"/></button><p>Connect your wallet to get started.</p></section></main>
 <footer className="landing-footer wrap"><a className="brand" href="#"><Mark/><span>mercury<span className="brand-dot">.</span></span></a><p>Intelligence, with ownership.</p><div><a href="#ecosystem">Ecosystem</a><a href="#how-it-works">How it works</a><span>© {new Date().getFullYear()} Mercury</span></div></footer></div>;
}
