// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IERC6551Registry$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IERC6551Registry";
  readonly sourceName: "src/interfaces/IERC6551Registry.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"implementation","type":"address"},{"internalType":"bytes32","name":"salt","type":"bytes32"},{"internalType":"uint256","name":"chainId","type":"uint256"},{"internalType":"address","name":"tokenContract","type":"address"},{"internalType":"uint256","name":"tokenId","type":"uint256"}],"name":"createAccount","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/interfaces/IERC6551Registry.sol";
  readonly buildInfoId: "solc-0_8_28-8e57c69064e09c2ee5831877a6700258a72b4c6d";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IERC6551Registry"]: IERC6551Registry$Type;
    ["src/interfaces/IERC6551Registry.sol:IERC6551Registry"]: IERC6551Registry$Type;
  }
}