// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IAgentVerifier$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IAgentVerifier";
  readonly sourceName: "src/interfaces/IAgentVerifier.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"tokenId","type":"uint256"},{"internalType":"address","name":"from","type":"address"},{"internalType":"address","name":"to","type":"address"},{"internalType":"bytes","name":"proof","type":"bytes"}],"name":"verifyTransfer","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/interfaces/IAgentVerifier.sol";
  readonly buildInfoId: "solc-0_8_28-8e57c69064e09c2ee5831877a6700258a72b4c6d";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IAgentVerifier"]: IAgentVerifier$Type;
    ["src/interfaces/IAgentVerifier.sol:IAgentVerifier"]: IAgentVerifier$Type;
  }
}